### ISSUE TITLE
Image expiration in canned responses

### ISSUE THREAD

**Issue by pete1854** [osTicket/osTicket-plugins#228]
Hi,

I'm trying to set up a collection of canned responses. I choose to insert an image into my response template using the image icon in the toolbar of the editor. I choose "Upload" and select an image. I return back to the editor and everything looks fine.

But - then, when I save the canned response - the image is broken, showing a generic "broken image" icon. 

**Before saving the canned reponse**

![image](https://user-images.githubusercontent.com/47314226/162002375-50637fa7-da03-4ed1-9c55-7e3cb0bbcd44.png)

**Immediately after saving the canned response**

![image](https://user-images.githubusercontent.com/47314226/162002687-bb36c4a5-5be8-47e8-bfa5-ece9a4c994d6.png)

I checked the HTML for the canned response template and discovered an `expires `parameter in the image url. 

`<img src="/file.php?key=unxuk5zql07es-flo5vtd0e_fnje0r4s&expires=1649289600&signature=3408812f66d4afe652f380392eb9a6bdbc4278cc&id=27"...`

What is this, and why would I want an image to expire in a system wide canned response intended for indefinit use? Is it possible to configure this parameter in some way to prolong expiration (ideally, I would like to be able to skip expiration all together in canned responses).

Or - could these issues come from some configuration error from my side? I honestly have no clue.

Kind regards,
Peter

**Comment by JediKev** [comment]
@pete1854 

Thank you for the issue report. I would like to first mention that you posted this in the wrong repo. This is the repo for osTicket Plugins; you are looking for the [osTicket core repo here](https://github.com/osTicket/osTicket).

With this being said, I am using v1.16.1 and PHP 8.0 and cannot see an expiration at all. When I upload an inline image to a Canned Response it shows the CID for the image (eg. `<img src="cid:-fdavasdppbin6klasdfksgl2gva" data-image="-D_SiaeigYYbGg5bcOpKv02beSGL2GVA" alt="image" />`). There is a current bug where since a previous major redactor upgrade the inline images were borked on display in Canned Responses specifically. When you select the Canned Response to use in a Reply, attach it via a Filter, etc. the inline images still function and display properly; it's just the display in the edit view for Canned Responses that's borked. Rest assured this is on our bug sheet to look into further.

Cheers.

**Comment by pete1854** [comment]
Oops - sorry for not making sure I was posting in the correct forum. My bad.

I'm happy to hear this is just an issue when editing the CR in the editor. I can live with that 😊

Thanks, @JediKev for your quick response!

Cheers,
Peter

**Comment by pete1854** [comment]
Resolved
