### ISSUE TITLE
Cannot populate user data from Active directory but search works fine

### ISSUE THREAD

**Issue by smfilip** [osTicket/osTicket-plugins#247]
Hello, I just recently installed osTicket and LDAP Authentication and Lookup plugin.
I successfully configured the plugin, search works, but nothing happens when I click on the found user (the field does not populate).
I am posting screenshots.

![1](https://user-images.githubusercontent.com/116871091/198528354-231dcc1f-5c8f-49b2-883f-4df731c17921.jpg)
![2](https://user-images.githubusercontent.com/116871091/198528349-30b824bf-9ba8-4374-b289-b07833d62ce8.jpg)

LDAP version 0.6.2
osTicket Version v1.17 (1d8b790)
Web Server Software Microsoft-IIS/10.0
MySQL Version 5.5.45
PHP Version 8.0.0

Is there any current solution, I am finding only posts 4-5 years old
Users and agents can normally log in with an AD user/password when opening tickets by themselves, but we need Agents to be able to create tickets for our users

**Comment by smfilip** [comment]
Gave up on this, developer not interested in fixing.

**Comment by JediKev** [comment]
@smfilip 

So we don’t respond immediately and you give up ???

Anyways, see this:
- https://github.com/osTicket/osTicket/pull/6333

Cheers.

**Comment by smfilip** [comment]
Believe me that I have tried almost 20 "fixes" and none solved this, I have a production environment with at least 5 tools/software that reads AD without any problems.
That being said, [https://github.com/osTicket/osTicket/pull/6333](url) doesn't help either

**Comment by JediKev** [comment]
@smfilip 

Do you still get 404 with the mentioned changes applied? If it gets decoded properly it should match here:
- https://github.com/osTicket/osTicket/blob/1.17.x/scp/ajax.php#L119

The URL in your screenshot decodes to `/users/select/auth:ldap:xxx` which is indeed correct and should be matching with the changes I mentioned above applied.

Have you checked your IIS logs to see if maybe it’s blocking the URL due to "potentially dangerous Request.Path"? Someone had something similar happen when `:` is present in the URL (which is what this URL has when properly decoded) and they [posted a fix here](https://forum.osticket.com/d/101808-oauth2-issues-reverse-proxy/8).

Cheers.

**Comment by smfilip** [comment]
Still 404 together with some warning from Chrome
![Capture](https://user-images.githubusercontent.com/116871091/198852202-3c86fed2-5943-4b54-867b-19b2c6a5f1e8.jpg)



Also already tried to modify web.config, nothing changed :(
By following the link in the error log, I simply get text page with "User not found"
Here is log from Fiddler
![cap2](https://user-images.githubusercontent.com/116871091/198852661-3d927708-9bc4-4a87-be40-8af3a697b1f2.jpg)

I must mention that when AD user try to login and open the ticket with their AD User/PW, everything works, the problem is only on this page
