### ISSUE TITLE
Change secret-access-key value from SQL

### ISSUE THREAD

**Issue by jevilla94** [osTicket/osTicket-plugins#252]
Best regards

I am trying to configure a script that allows me to automatically configure the plugin for s3, however I have problems identifying the encryption of secret-access-key since the real value does not correspond to the one in the database.

I thank you in advance for any information you can give me.

**Comment by JediKev** [comment]
@jevilla94 

This is more of a question that is better suited for [our Forum](https://forum.osticket.com). In the future please use our Forum to ask any questions you may have.

With that being said, I will go ahead and answer you since I’m already here. You can see below where we decrypt:
- https://github.com/osTicket/osTicket-plugins/blob/develop/storage-s3/config.php#L97-L99

… and where we encrypt:
- https://github.com/osTicket/osTicket-plugins/blob/develop/storage-s3/config.php#L127-L128

It uses the salt and the plugin namespace to encrypt the access key.

Cheers.
