### ISSUE TITLE
php >= 8.x compatibility

### ISSUE THREAD

**Issue by Cm-8** [osTicket/osTicket-plugins#253]
Hi to all,

the plugin [storage_fs](https://github.com/osTicket/osTicket-plugins/tree/develop/storage-fs) is compatible with php >= 8.0?

thanks

**Comment by JediKev** [comment]
@Cm-8 

Please use [our Forum](https://forum.osticket.com) next time. Github is a place to report bugs, make a feature request, or submit a pull request. If you have questions, etc. you will need to use the Forum.

Since you opened this here I will go ahead and provide an answer:
Yes, the latest `storage-fs.phar` build is PHP 8.0-8.1 compatible (just like the latest releases of osTicket).

Cheers.
