### ISSUE TITLE
Login issues with LDAP

### ISSUE THREAD

**Issue by sandip22c** [osTicket/osTicket-plugins#47]
Hi,

I have installed osTicket & configured for ldap with auth-ldap plugin with below config.

Default Domain: example.com
DNS Servers: ns1.example.com
LDAP servers: ldap.example.com
No TLS
Search User: uid=webapp-ro,ou=Employees,ou=People,dc=example,dc=com
Password: ******
Search Base: ou=People,dc=example,dc=com
LDAP Schema: (Tried with auto & posix acc)
Staff Authentication & Client Authentication Enabled

But when I try to login it gives below error in http error logs.

[Wed Aug 13 05:51:39 2014] [error] [client 172.16.0.84] PHP Fatal error:  Call to a member function bind() on a non-object in /var/www/html/osticket/upload/include/plugins/auth-ldap/authentication.php on line 211, referer: http://osbeta.support.example.com/scp/login.php
[Wed Aug 13 05:51:47 2014] [error] [client 172.16.0.84] PHP Fatal error:  Call to a member function bind() on a non-object in /var/www/html/osticket/upload/include/plugins/auth-ldap/authentication.php on line 211, referer: http://osbeta.support.example.com/login.php

Please help.

**Comment by sandip22c** [comment]
OS: CentOS release 6.5 (Final)   x86_64
PHP: 5.5.14
MySQL: 5.6.20
Httpd: 2.2.15

**Comment by ntozier** [comment]
What version of osTicket?
What version of the LDAP plugin?

My first thought is CentOS, shut off SELinux and try again. (since its the #1 reason for CentOS users to have issues).  

My second thought is that example.com is actually a domain, with real dns.  So if you setup it up like you indicated that would probably cause some issues.  If you just use that to sterilize your server config you can ignore this paragraph.

I haven't really been keeping up with all the changes to PHP recently, but its possible that 5.5 is just plain too new and deprecates something which worked fine in 5.3/5.4.  

It's also possible that your LDAP server isn't answering the request, causing no results, which could cause the "non object" error.

**Comment by sandip22c** [comment]
Sorry for delayed reply.

We have removed the ldap part.

Thanks for your help.

**Comment by greezybacon** [comment]
@sandip22c Did you just give up and uninstall the LDAP plugin?
